### ISSUE TITLE
【提问】0.1.16 及其以后版本，需要glibc 2.32 2.33 2.34，ubuntu 20 不再支持了么？

### ISSUE THREAD

**Issue by CatOverrun** [biliup/biliup-rs#101]
ubuntu 20的ldd是9.9，最高只能到glibc 2.31
如果要运行0.1.16 或者0.1.17，只能系统升级到ubuntu22。但系统上还有别的程序，dotnet 7.0在ubuntu 22上的支持也不是很好。程序没有办法兼容么？

**Comment by puzzlemoondev** [comment]
我有個v0.1.17的docker image是用debian bullseye編譯的，你可以試試看。
https://github.com/puzzlemoondev/biliup-rs-docker

bullseye的glibc：
https://packages.debian.org/source/bullseye/glibc

**Comment by CatOverrun** [comment]
由于个人脚本原因，用的是python的subprocess来操作的，docker版确实可以运行，但会增加很多步骤，要改脚本，就要测试。
加上不敢动ubuntu 20自带的glibc6，整个系统依赖这个，怕动了不能再开机。
随尝试几次后改用musl静态编译版解决问题。只求大佬以后能保持musl版的发布更新。😥
