### ISSUE TITLE
关于--up-close-reply和--up-close-danmu

### ISSUE THREAD

**Issue by nankaine** [biliup/biliup-rs#115]
首先，感谢biliup-rs这个作品。
现在在linux上使用最新版的biliup-rs的过程中，以命令行的形式上传视频，示例如下：
`./biliup-rs upload --tag=测试 --tid=21 --up-close-danmu --up-close-reply 视频.mp4`
可以正常上传成功，并通过审核。 但是这个视频却可以正常进行评论和发送弹幕。

而且在官方网页端上传同一个视频，手动选择了禁止评论和发送弹幕，这个投稿就禁止了评论和弹幕。

不知道您是否linux使用最新的biliup-rs复现--up-close-reply和--up-close-danmu无效的情况。

**Comment by Kataick** [comment]
简介右边没文字说明的都是暂未实现的功能
