### ISSUE TITLE
kodo线路上传问题

### ISSUE THREAD

**Issue by AppreciateL** [biliup/biliup-rs#132]
海外使用kodo线路分p投稿，在第一个视频显示正常上传（带宽完全拉满）完成以后出现EOF，无法继续上传后续的视频
![1](https://github.com/biliup/biliup-rs/assets/140914745/f04df947-1a5e-49df-91bf-62c9a5d7c3d9)
测试其他国内线路分p的多个视频都可以按序正常上传投稿（速度会慢一些）

**Comment by Canda15** [comment]
kodo已经很久不能用了。qn和ws上传线路也有问题，只能拉起一个线程。腾讯云内外网线路也均无法使用的。

**Comment by AppreciateL** [comment]
> kodo已经很久不能用了。qn和ws上传线路也有问题，只能拉起一个线程。腾讯云内外网线路也均无法使用的。

了解了，非常感谢
