### ISSUE TITLE
请问带接口参数的命令该如何正确输入

### ISSUE THREAD

**Issue by yibingchaoyue** [biliup/biliup-rs#163]
biliup append  --vid BV号  --submit app --line ws --limit 30 /root /1.flv 
error: unexpected argument '--submit' found
bv号我隐藏了 但输入这个接口参数就会错误  不输就不会

**Comment by xxxxuanran** [comment]
--submit 参数仅限 upload 方法，append 方法不支持

**Comment by xxxxuanran** [comment]
```
Error: error decoding response body

Caused by:
EOF while parsing a value at line 1 column 0
```
正常来说这里会打印原数据，如果确实没有打印，那么无法修复这个问题。
