### ISSUE TITLE
[已解决]HiRes支持错误，代码如下，如何解决？

### ISSUE THREAD

**Issue by kimycai** [biliup/biliup-rs#61]
windows 10系统
命令：biliup upload  --tag 音乐 --tid 130 --hires 1 MTV.mkv
出现以下错误信息
error: Found argument '--hires' which wasn't expected, or isn't valid in this context

  If you tried to supply '--hires' as a value rather than a flag, use '-- --hires'

**Comment by ForgQi** [comment]
用的哪个版本

**Comment by kimycai** [comment]
> 用的哪个版本

最新版

**Comment by ForgQi** [comment]
版本号

**Comment by kimycai** [comment]
> 版本号

v0.1.15

**Comment by ForgQi** [comment]
`biliup help upload`可以查看所有支持的选项

**Comment by kimycai** [comment]
> `biliup help upload`可以查看所有支持的选项

有的才是被支持的？而不是看readme页面上有的？

**Comment by kimycai** [comment]
> biliup help upload

命令行显示没有--hires参数，但readme上写了是有的

**Comment by ForgQi** [comment]
没有就说明你不是0.1.15版本

**Comment by kimycai** [comment]
> 没有就说明你不是0.1.15版本

D:\biliupR-v0.1.15-x86_64-windows>biliup help upload
上传视频

Usage: biliup upload [OPTIONS] [VIDEO_PATH]...

Arguments:
  [VIDEO_PATH]...  需要上传的视频路径,若指定配置文件投稿不需要此参数

Options:
  -c, --config <FILE>              Sets a custom config file
  -l, --line <LINE>                选择上传线路 [possible values: bda2, ws, qn, kodo, cos, cos-internal]
      --limit <LIMIT>              单视频文件最大并发数 [default: 3]
      --copyright <COPYRIGHT>      是否转载, 1-自制 2-转载 [default: 1]
      --source <SOURCE>            转载来源 [default: ]
      --tid <TID>                  投稿分区 [default: 171]
      --cover <COVER>              视频封面 [default: ]
      --title <TITLE>              视频标题 [default: ]
      --desc <DESC>                视频简介 [default: ]
      --dynamic <DYNAMIC>          空间动态 [default: ]
      --tag <TAG>                  视频标签，逗号分隔多个tag [default: ]
      --dtime <DTIME>              延时发布时间，距离提交大于4小时，格式为10位时间戳
      --interactive <INTERACTIVE>  [default: 0]
      --mission-id <MISSION_ID>
      --dolby <DOLBY>              是否开启杜比音效, 0-关闭 1-开启 [default: 0]
      --no-reprint <NO_REPRINT>    0-允许转载，1-禁止转载
      --up-selection-reply
      --up-close-reply
      --up-close-danmu
      --open-elec <OPEN_ELEC>      是否开启充电, 0-关闭 1-开启
  -h, --help                       Print help information

以上是命令行的全部信息，包括路径信息，原汁原味

**Comment by ForgQi** [comment]
我知道了，是这边疏忽了

**Comment by kimycai** [comment]
那就静待更新了

**Comment by kimycai** [comment]
--hires <LOSSLESS_MUSIC>       是否开启 Hi-Res, 0-关闭 1-开启 [default: 0]

能否将hires设为默认开启，因为如果上传的音频不符合hires标准，也不影响视频的播放，如果后期更换为hires音轨，也只用替换新的含hires音轨的视频源，而不用重新投稿。

**Comment by kimycai** [comment]
请问 --hires 这个参数功能是被移除了还是未在新版更新？

**Comment by kimycai** [comment]
> 请问充电视频能控制预览时长吗

不支持
